In [26]:
import pandas as pd
df = pd.read_csv('indianEco.csv')
df.head()

,Year,Country Name,GDP (current US$),GDP per capita (current US$),GDP growth (annual %),Imports of goods and services (% of GDP),Exports of goods and services (% of GDP),"Total reserves (includes gold, current US$)","Inflation, consumer prices (annual %)","Population, total",Population growth (annual %),"Life expectancy at birth, total (years)"
0,1960,India,3.702988e+10,82,0.00,6.83,4.46,6.745366e+08,1.78,445954579,2.31,41.13
1,1961,India,3.923244e+10,85,3.72,5.96,4.30,6.663571e+08,1.70,456351876,2.33,41.74
2,1962,India,4.216148e+10,90,2.93,6.03,4.17,5.127918e+08,3.63,467024193,2.34,42.34
3,1963,India,4.842192e+10,101,5.99,5.91,4.28,6.078625e+08,2.95,477933619,2.34,42.94
4,1964,India,5.648029e+10,116,7.45,5.69,3.73,4.991451e+08,13.36,489059309,2.33,43.57

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 11 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Year                                           61 non-null     int64
 1   GDP (current US$)                              61 non-null     float64
 2    GDP per capita (current US$)                  61 non-null     int64
 3   GDP growth (annual %)                          61 non-null     float64
 4   Imports of goods and services (% of GDP)       61 non-null     float64
 5   Exports of goods and services (% of GDP)       61 non-null     float64
 6    Total reserves (includes gold, current US$)   61 non-null     float64
 7   Inflation, consumer prices (annual %)          61 non-null     float64
 8   Population, total                              61 non-null     int64
 9   Population growth (annual %)                   61 non-null     float64
 10  Life expectancy at birth, total (years)        61 non-null     float64
dtypes: float64(8), int64(3)
memory usage: 5.4 KB

In [27]:
df2 = df.drop("Country Name",axis = 1, inplace=True)

df.head()

,Year,GDP (current US$),GDP per capita (current US$),GDP growth (annual %),Imports of goods and services (% of GDP),Exports of goods and services (% of GDP),"Total reserves (includes gold, current US$)","Inflation, consumer prices (annual %)","Population, total",Population growth (annual %),"Life expectancy at birth, total (years)"
0,1960,3.702988e+10,82,0.00,6.83,4.46,6.745366e+08,1.78,445954579,2.31,41.13
1,1961,3.923244e+10,85,3.72,5.96,4.30,6.663571e+08,1.70,456351876,2.33,41.74
2,1962,4.216148e+10,90,2.93,6.03,4.17,5.127918e+08,3.63,467024193,2.34,42.34
3,1963,4.842192e+10,101,5.99,5.91,4.28,6.078625e+08,2.95,477933619,2.34,42.94
4,1964,5.648029e+10,116,7.45,5.69,3.73,4.991451e+08,13.36,489059309,2.33,43.57

In [ ]:
df